_commit: 45a69bc
_src_path: gh:bswck/skeleton
author_username: ITeapotPL
docs: true
docs_slug: iteapot-discord-bot
email_address: kontakt@iteapot.pl
github_username: ITeapotPL
license_name: GPL-3.0
org_full_name: ITeapot
package_name: discord_bot
project_description: A Discord Bot for the ITeapot team. Powered by hikari, crescent
    & miru.
publish_on_pypi: false
python_version: '3.10'
repo_name: discord-bot
test_suite: true
use_precommit: true
visibility: public
